#!/usr/bin/env sh

cd maia-build && ./gradlew clean build test
cd ../maia-build-moa && ./gradlew clean build test
cd ../maia-arff && ./gradlew clean build test
cd ../maia-configure && ./gradlew clean build test
cd ../maia-dataset && ./gradlew clean build test
cd ../maia-json-configuration && ./gradlew clean build test
cd ../maia-learner && ./gradlew clean build test
cd ../maia-learner-factory && ./gradlew clean build test
cd ../maia-moa-dataset-nodes && ./gradlew clean build test
cd ../maia-moa-datasets && ./gradlew clean build test
cd ../maia-moa-learners && ./gradlew clean build test
cd ../maia-primitive && ./gradlew clean build test
cd ../maia-standard-dataset-nodes && ./gradlew clean build test
cd ../maia-standard-datasets && ./gradlew clean build test
cd ../maia-standard-learner-nodes && ./gradlew clean build test
cd ../maia-standard-learners && ./gradlew clean build test
cd ../maia-standard-nodes && ./gradlew clean build test
cd ../maia-standard-types && ./gradlew clean build test
cd ../maia-topology && ./gradlew clean build test
cd ../maia-topology-json && ./gradlew clean build test
cd ../maia-util && ./gradlew clean build test
