cd ../maia-build && gradlew.bat clean build test
cd ../maia-build-moa && gradlew.bat clean build test
cd ../maia-arff && gradlew.bat clean build test
cd ../maia-configure && gradlew.bat clean build test
cd ../maia-dataset && gradlew.bat clean build test
cd ../maia-json-configuration && gradlew.bat clean build test
cd ../maia-learner && gradlew.bat clean build test
cd ../maia-learner-factory && gradlew.bat clean build test
cd ../maia-moa-dataset-nodes && gradlew.bat clean build test
cd ../maia-moa-datasets && gradlew.bat clean build test
cd ../maia-moa-learners && gradlew.bat clean build test
cd ../maia-primitive && gradlew.bat clean build test
cd ../maia-standard-dataset-nodes && gradlew.bat clean build test
cd ../maia-standard-datasets && gradlew.bat clean build test
cd ../maia-standard-learner-nodes && gradlew.bat clean build test
cd ../maia-standard-learners && gradlew.bat clean build test
cd ../maia-standard-nodes && gradlew.bat clean build test
cd ../maia-standard-types && gradlew.bat clean build test
cd ../maia-topology && gradlew.bat clean build test
cd ../maia-topology-json && gradlew.bat clean build test
cd ../maia-util && gradlew.bat clean build test
